### ISSUE TITLE
Support tuples

### ISSUE THREAD

**Issue by BlackEdder** [BlackEdder/painlessjson#13]
I don't think that we support tuples at the moment. Easiest is probably to convert them into an array of JSONValues.

**Comment by Zalastax** [comment]
Unnamed tuples work good already.

```
unittest
{
      Tuple!(int, int) point;
      point[0] = 5;
      point[1] = 6;
      assert(jsonEquals(toJSON(point), q{{"_0":5,"_1":6}}));
}
```

Passes the test. But named tuples have the same field multiple times.

```
unittest
{
      Tuple!(int, "x", int, "y") point;
      point.x = 5;
      point.y = 6;
      writeln(toJSON(point));
}
```

produces {"x":5,"_0":5,"y":6,"_Tuple_super":{"_0":5,"_1":6},"_1":6}. fromJSON will work if you pass this string into it and it will also work if you pass in {"x":5,"y":6}. Do we really want to do something special to make the output of named tuples smaller?

**Comment by Zalastax** [comment]
There seems to be a bug in the compile-chain. See https://github.com/Zalastax/painlessjson/commit/68db13aaac66bd238ca5c321f5f6ea887f83d1cb
auto h = cast(Object)(point); seems to compile on Travis, but not on my machine. Could you verify this on your machine?

**Comment by BlackEdder** [comment]
I get the following error when I try "dub test" on your branch (that's the same error as travis gives):

```
$ dub test
Generating test runner configuration '__test__library__' for 'library' (library).
painlessjson: ["painlessjson"]
Building painlessjson configuration "__test__library__", build type unittest.
Compiling...
source/painlessjson/painlessjson.d(308): Error: template std.typecons.Tuple!(int, "x", int, "y").Tuple.opAssign cannot deduce function from argument types !()(Tuple!(int, "x", int, "y")*), candidates are:
/home/edwin/nix/store/mw5af4rk76hmzdl6a6x0djjylr4jgkfb-dmd-2.066.1/include/d2/std/typecons.d(532):        std.typecons.Tuple!(int, "x", int, "y").Tuple.opAssign(R)(auto ref R rhs) if (areCompatibleTuples!(typeof(this), R, "="))
source/painlessjson/painlessjson.d(207): Error: template instance painlessjson.painlessjson.fromJSON!(Tuple!(int, "x", int, "y")) error instantiating
FAIL .dub/build/__test__library__-unittest-linux.posix-x86_64-dmd-3A3FF5EB4180625B6E317D712B675092 __test__library__ executable
Error executing command test: DMD compile run failed with exit code 1
```

**Comment by Zalastax** [comment]
We should still add the unittests. And since the linux version is different file a bug report.

**Comment by Zalastax** [comment]
Before submitting a bug, we need a minimal example that shows the bug.
Does this code compile for you?

```
import std.stdio;
import std.typecons;

static if (!is(typeof(writeln)))
    alias writefln writeln;

void main()
{
    Tuple!(int,int) point;
    cast(Object)(point);
    writeln("Hello world!");
}
```

**Comment by BlackEdder** [comment]
That produces the following error for me

```
$ dmd test.d
test.d(10): Error: cannot implicitly convert expression (tuple(cast(Object)point._expand_field_0, cast(Object)point._expand_field_1)) of type (int, int) to object.Object
```

Are you sure it is supposed to work :)

**Comment by Zalastax** [comment]
No it shouldn't, but I thought it might have on linux. In my commit I added the cast(Object) before the assert and since it didn't come up as an compile error in Travis I thought it worked there. Could you debug why

```
static if (__traits(compiles, cast(Object)(t)) && __traits(compiles,
         new T))
     {
         t = new T;
     }
```

calls new on Tuples? I might need to set up a linux VM to test things like these myself.

**Comment by BlackEdder** [comment]
Ah, I see what you mean. Will hopefully have some time to look at it tomorrow. Are you on OSX or windows?

**Comment by Zalastax** [comment]
I am on windows, and now have DMD set up on an Ubuntu VM.
I have found the smallest code that shows the bug.

```
import std.typecons;

void main()
{
     Tuple!(int, "x", int, "y") point;
     static if (__traits(compiles, {auto newPoint = cast(Object)(point);}))
     {
              {auto newPoint = cast(Object)(point);}
     }
}
```

**Comment by BlackEdder** [comment]
It is quite strange that this bug occurs with all compilers on Linux
(according to Travis) which suggests its a Phobos bug.

I guess we should file a bug on slang and add a specific fromjson override
for tuples to work around the bug.

**Comment by BlackEdder** [comment]
s/slang/dlang

**Comment by Zalastax** [comment]
I filed a bug. https://issues.dlang.org/show_bug.cgi?id=14093

**Comment by BlackEdder** [comment]
Thanks for solving this @Zalastax . Closing
