### ISSUE TITLE
publish the docs as gh-pages

### ISSUE THREAD

**Issue by MartinNowak** [BlackEdder/painlessjson#15]
Much nicer to quickly have a look at the package.
See https://github.com/MartinNowak/bloom for an example.

**Comment by Zalastax** [comment]
That's great!
Is there a way to make Travis generate it automatically?

**Comment by MartinNowak** [comment]
Yes, you need a small script like that.
[Publishing gh-pages with Travis-CI — Medium](https://medium.com/@nthgergo/publishing-gh-pages-with-travis-ci-53a8270e87db)

**Comment by MartinNowak** [comment]
Finally got it working.
https://travis-ci.org/MartinNowak/bloom/builds/49049856

**Comment by Zalastax** [comment]
I'll take a look on that. I'll also have to search for some nice looking theme for the generated output. Or investigate the other generators and see if they output something nicer looking. If I remember correctly it's quite hard to get good information about the ddoc output so I'll probably do a write up about what i find out.

**Comment by BlackEdder** [comment]
@Zalastax A basic version of this is now working in #16. Of course any improvements to layout templates would be appreciated.

**Comment by Zalastax** [comment]
I'll open a new issue about that.
