### ISSUE TITLE
FromJson with an array of structs

### ISSUE THREAD

**Issue by kingsleyh** [BlackEdder/painlessjson#35]
Hi I see its possible to convert an array of structs to json, but what about the other direction?

```
// in the docs
Point[] ps = [Point(-1, 1), Point(2, 3)];
assertEqual(toJSON(ps).toString, q{[{"x":-1,"y":1},{"x":2,"y":3}]});

// but can this be supported?
struct Point { int x; int y}
assertEqual(fromJSON!Point[](parseJSON(q{{"x":-1,"y":2},{"x":3,"y":4}})), [Point(-1,1),Point(3,4)]);
```

**Comment by BlackEdder** [comment]
Hi,

That should already work. Do you get any errors when trying that?

Edwin

**Comment by kingsleyh** [comment]
Hi - sorry yes you are right :) totally awesome job on the painlessjson library! I'm new to D and so had some syntax errors in my code. All good now :)

**Comment by Zalastax** [comment]
I added the code from your question with corrected syntax to the unit tests Feel free to open more issues if there is something else you think is unclear and star if you want to add visibility to our work.
