### ISSUE TITLE
From Json not creating nested array of struct

### ISSUE THREAD

**Issue by kingsleyh** [BlackEdder/painlessjson#36]
Hi - am I doing something wrong here?

```
import std.json;
import painlessjson;
import std.array;


 struct Label{
    string name;
  }

  struct Scenario{
    string name;
    Label[] labels;
  }

  Scenario[] scenarios = fromJSON!(Scenario[])(parseJSON(q{[{"name":"scenario1","labels":   [{"name":"label1"}]}]}));
 writeln(scenarios.front.labels);
```

> Running unit tests
> []

scenarios should have a list of labels - but its empty. 
When I change Label[] labels to JSONValue labels and print it out I get this:

> Running unit tests
> [{"name":"label1"}]

so it looks like its finding the json ok - just not turning it into a Label[]

**Comment by Zalastax** [comment]
Have you defined Label and Scenario in an importable way? The fromJSON method need to be able to add an import yourmodule; to see the Label struct. Defining Label inside a function and then using it indirectly is unsupported.

```
 import std.json;
 import painlessjson;
 import std.array;
 import std.stdio;


  struct Label{
     string name;
   }

   struct Scenario{
     string name;
     Label[] labels;
   }

 unittest{
   Scenario[] scenarios = fromJSON!(Scenario[])(parseJSON(q{[{"name":"scenario1","labels":   [{"name":"label1"}]}]}));
   writeln(scenarios.front.labels);
 }
```

prints [Label("label1")]

**Comment by kingsleyh** [comment]
Yeah I tried putting the structs in a separate file and just importing them - but same error

**Comment by Zalastax** [comment]
Could you provide your complete solution that fails? I can't reproduce as it stands right now.

**Comment by kingsleyh** [comment]
I have put it in a repo:  https://github.com/kingsleyh/painlesstest

just run dub test in the root and you will see that the labels are empty

**Comment by Zalastax** [comment]
You found a bug in the code. We are mixing in an import statement, but it doesn't seem to work. I will have to spend some time on this.

**Comment by kingsleyh** [comment]
How is this test passing in your repo - it looks very similar to what in trying to do:

/// Array as member of other class
unittest
{
    // Types need to be defined in different module, otherwise 
    // type is not known at compile time
    import painlessjson.unittesttypes_local_import;

```
string jsonString = q{[ {"duration": "10"} ]};
Route[] routes = parseJSON(jsonString).fromJSON!(Route[]);
assertEqual(routes.length, 1);

jsonString = q{{"routes":[ {"duration": "10"} ] }};
JourneyPlan jp;
jp = parseJSON(jsonString).fromJSON!JourneyPlan;
assertEqual(jp.routes.length, 1);
```

}

**Comment by Zalastax** [comment]
I'll investigate further but it seems to be a bug with the compiler. moduleName!type doesn't seem to work if the type hasn't been imported yet.

**Comment by Zalastax** [comment]
I found what was wrong with my code!
I had to move the import code to before we check if the other mixin compiles. I also had a bad understanding of how moduleName works so I had wrapped my type in typeof() wich is bad since that removes information that moduleName needs.

**Comment by kingsleyh** [comment]
great! does that mean it's fixed? I've converted my code to use jsonizer - but I'm willing to move back to painlessjson if this functionality works - since it's the main thing I need.

**Comment by Zalastax** [comment]
The new release has the issue fixed. I hope it works for you as well.

**Comment by kingsleyh** [comment]
I've tested this issue and it's working now :)
