### ISSUE TITLE
Possibility of Boost License

### ISSUE THREAD

**Issue by Downchuck** [BlackEdder/painlessjson#40]
For the same reasons I put forward in the dproto project, would the painlessjson offers be willing to migrate to a Boost license? https://github.com/msoucy/dproto/issues/38

It appears that dproto will be using painlessjson as an optional dependency. I'm trying to keep a clear chain of Boost license (from d standard library through dproto). D standard lib is Boost.

**Comment by BlackEdder** [comment]
My main reason for using the BSD license was that even though I know most common licenses I don't really know the boost license and therefore wouldn't expect others to know it. I regard the BSD license easier for new contributors, because they will already know the gist of it. 

What is your objection against the BSD license?

Ping the other contributers: @Zalastax and @msoucy

**Comment by Zalastax** [comment]
I feel that MIT, BSD, and BOOST provide similar licenses and I would be OK with whatever choice is made.

**Comment by Downchuck** [comment]
Though a small point: The BSD license in the case of D requires that painlessjson be mentioned in documentation/help/about pages of the distribution to the end-user of a compiled program.

The Boost license requires that source code mention painlessjson, but once a program is compiled and distributed, there is no requirement of mentioning the D language, or any other Boost licensed components.

This is a bit easier and more flexible for application distributions to end users, though is at the opposite end of the spectrum from something like GPLv3.

The licenses are quite similar, but I feel that Boost is most appropriate for distributions to end-users as applications;  MIT/BSD are quite appropriate for server-side distributions (such as vibe-d), where again, the end-user has no idea what is running, but because it is run on a server, the license does does not impact them.

**Comment by BlackEdder** [comment]
OK I'm fine with changing it to be more inline with the D eco system. Will try to do this later this week. Seeing how @msoucy contributed solely to the README (and agreed changing to boost for dproto) I think we can move forward without waiting for his input, although I would still prefer to have an official aye or nay from him if he is listening :-).

**Comment by Downchuck** [comment]
@BlackEdder he has been responsive on dproto, available more than once a month.

**Comment by msoucy** [comment]
Aye

Sorry, this fell between the cracks
