### ISSUE TITLE
Split traits templates into separate library?

### ISSUE THREAD

**Issue by msoucy** [BlackEdder/painlessjson#47]
Are there any plans to split https://github.com/BlackEdder/painlessjson/blob/master/source/painlessjson/traits.d into a separate library? These templates seem quite useful even in situations where one isn't using json, as a general-purpose uda library.

**Comment by Zalastax** [comment]
I had no plans for that but it's OK for me to copy them to another repo and leave a contribution note. Especially if you create a pull request here to use that repo instead!

**Comment by msoucy** [comment]
OK if I use the name "painlesstraits"?

**Comment by Zalastax** [comment]
Awesome!
@BlackEdder ?

**Comment by msoucy** [comment]
Packaged it up for you: https://github.com/msoucy/painlesstraits

Making a pull request momentarily
