### ISSUE TITLE
Make (de)serialization more configurable. 

### ISSUE THREAD

**Issue by Zalastax** [BlackEdder/painlessjson#5]
Continuation from discussion in pull request https://github.com/BlackEdder/painlessjson/pull/1
The underscore added to toJSON and fromJSON is because the fromJSON i  painlessjson can be called like object.fromJSON(); using UFCS. It might be possible to fix but I found others with similiar problems on forum.dlang.org so I stopped trying. Perhaps a smarter trait-check could figure it out. Would be great to solve this since if we use my ideas below someone might select a method we can't call.

I really like annotations and think they are a the right tool for configuring something like this. They are a bit rigid but we can't get around that without using dynamic configurable (de)serializer-objects which probably would require magic or runtime reflection.
I think https://github.com/FasterXML/jackson-annotations handles configuration in a great way. It works by default, and it's easy to add annotations to remove values or rename them.
#### Serialization
- @property methods without parameters and visible fields gets serialized.
- When serialized the values will use the exact name for the method or visible field, unless overridden by annotation @SerializedName("otherName").
- If a method with annotation @ToJSON is present the other annotations will do nothing?
#### Deserialization

When deserializing we might need to be flexible. I could see two modes that could be configured using annotation on the class:
- Find all @property that takes one parameter. Disable using @JsonIgnore/@NoJSON or equivalent.
- Find only the methods that are enabled using @SerializedName or @JSON or equivalent.

A third mode could be used without needing class annotation:
- @FromJSON to select a constructor or method to use. Right now it could just take a JSONValue. In the future I want it to be like Jackson and be able to send multiple arguments by looking at the parameters name or annotations. If this is present all the other annotations will do nothing?
  Perhaps if we have @FromJSON and @ToJSON they could call painlessjson for a version that ignores those annotations and then just fix the result?
#### Final points

I like the concept of having sensible defaults and have the simple case work out of the box.The problem is making it customizable and I think annotations is the solution. The alternatives I see are option-objects, string-mixin-templates, and Strategy pattern(using templates and opCall or delagates).

**Comment by BlackEdder** [comment]
Sounds good. A couple of suggestions though. 

Firstly, I'd try to turn this in a more general (de)serialisation routine. What I imagine is a template (de)serialisation method that you provide a function of what to do with the actual data. serialize( (a) { return a.toJSON; } )( serializableObject ), with would return a JSONValue[string] associative array (indexes are the names). (By default it would return a Variant[string]?)

To keep the simple case working I would also try to support _toJSON/_fromJSON on top of @ToJSON/@FromJSON.

### Serialization
- Should respect @NoJSON/@JSONIgnore (or @SerialIgnore)

Other than that, sounds good and I would certainly be happy to pull such an update/give any help I can.

**Comment by Zalastax** [comment]
This issue is ready to be closed. Further improvements should use a new issue.
